name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Generate IDE Helper Files
      run: |
        php artisan ide-helper:generate
        php artisan ide-helper:meta
        php artisan ide-helper:models --nowrite
    - name: Check if IDE Helper files are up to date
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "IDE Helper files have been updated. This is expected and won't cause the pipeline to fail."
          echo "Changes detected in the following files:"
          git status --porcelain
        else
          echo "No changes detected in IDE Helper files."
        fi
      continue-on-error: true
    - name: Execute tests (PEST)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/pest
    - name: Check code style (Laravel Pint)
      run: vendor/bin/pint --test
    - name: Run static analysis (PHPStan)
      run: vendor/bin/phpstan analyse

